import{analyzeOffer,safeParse}from'./logic.js';const $=s=>document.querySelector(s),form=$('#offer-form'),KEY='offersignal-checks-v1';let current=null;const API_BASE=globalThis.OFFERSIGNAL_API_BASE||'';
function input(){const f=new FormData(form);return{label:f.get('label'),channel:f.get('channel'),senderEmail:f.get('senderEmail'),message:f.get('message'),applied:f.get('applied')==='on',interviewed:f.get('interviewed')==='on',verified:f.get('verified')==='on'};}
function showToast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2200);}
function render(result){current=result;$('#empty-output').hidden=true;$('#output').hidden=false;$('#result-name').textContent=result.label;const tier=$('#result-tier');tier.textContent=result.title;tier.className=`tier tier-${result.level}`;$('#result-summary').textContent=result.summary;$('#score-bar').style.width=`${result.score}%`;const findings=$('#findings');if(!result.matches.length){const el=document.createElement('div');el.className='finding none';el.innerHTML='<div class="finding-mark">✓</div><div><strong>No listed patterns matched</strong><span>Continue with independent identity and role verification.</span></div>';findings.replaceChildren(el);}else findings.replaceChildren(...result.matches.map((x,i)=>{const el=document.createElement('div');el.className='finding';const mark=document.createElement('div');mark.className='finding-mark';mark.textContent=String(i+1).padStart(2,'0');const text=document.createElement('div'),strong=document.createElement('strong'),span=document.createElement('span');strong.textContent=x.title;span.textContent=x.why;text.append(strong,span);el.append(mark,text);return el;}));$('#actions').replaceChildren(...result.actions.map(x=>{const li=document.createElement('li');li.textContent=x;return li;}));}
function items(){return safeParse(localStorage.getItem(KEY)||'[]');}function save(items){localStorage.setItem(KEY,JSON.stringify(items));renderSaved();}
function renderSaved(){const wrap=$('#saved-list'),checks=items();if(!checks.length){wrap.innerHTML='<div class="saved-empty">Nothing saved. Completed checks stay private unless you choose “Save locally.”</div>';return;}wrap.replaceChildren(...checks.map((c,i)=>{const el=document.createElement('article');el.className='saved-card';const h=document.createElement('h3');h.textContent=c.label;const p=document.createElement('p');p.textContent=`${new Date(c.createdAt).toLocaleDateString()} · ${c.title} · ${c.matches.length} pattern${c.matches.length===1?'':'s'}`;const open=document.createElement('button');open.className='button ghost';open.textContent='Review';open.onclick=()=>{render(c);location.hash='checker';};const del=document.createElement('button');del.className='link-button danger';del.textContent='Delete';del.onclick=()=>{const next=items();next.splice(i,1);save(next);};el.append(h,p,open,del);return el;}));}
async function shareCheck(){if(!current)return;if(!API_BASE){showToast('Team saving unavailable offline');return;}const button=$('#share-check');button.disabled=true;try{const{message,senderEmail,...privacySafe}=current;const response=await fetch(`${API_BASE.replace(/\/$/,'')}/api/v1/checks`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(privacySafe)});if(!response.ok)throw new Error('Server rejected the result');const data=await response.json();showToast(`Saved to team vault: ${data.id.slice(0,8)}`);}catch(error){showToast('Could not save; check remains local');}finally{button.disabled=false;}}
form.addEventListener('submit',e=>{e.preventDefault();const err=$('#form-error');err.hidden=true;try{render(analyzeOffer(input()));}catch(error){err.textContent=error.message;err.hidden=false;err.scrollIntoView({behavior:'smooth'});}});form.addEventListener('reset',()=>setTimeout(()=>{current=null;$('#output').hidden=true;$('#empty-output').hidden=false;$('#form-error').hidden=true;},0));
$('#sample-button').onclick=()=>{form.elements.label.value='Catalog quality assistant — sample';form.elements.channel.value='whatsapp';form.elements.senderEmail.value='talentdesk2026@gmail.com';form.elements.message.value='Urgent remote opportunity. Complete sets of product optimization tasks and earn $500 daily. Recharge your account with USDT to unlock your commission. Act now within 2 hours.';form.elements.applied.checked=false;form.elements.interviewed.checked=false;form.elements.verified.checked=false;render(analyzeOffer(input()));location.hash='checker';};
$('#save-check').onclick=()=>{if(!current)return;save([{...current,id:crypto.randomUUID()},...items()].slice(0,30));showToast('Saved on this device');};
$('#copy-checklist').onclick=async()=>{if(!current)return;const text=`OfferSignal verification checklist — ${current.label}\n\n${current.actions.map((x,i)=>`${i+1}. ${x}`).join('\n')}`;try{await navigator.clipboard.writeText(text);showToast('Checklist copied');}catch{showToast('Clipboard unavailable');}};
$('#export-checks').onclick=()=>{const data=items().map(({message,...rest})=>({...rest,messageOmitted:true}));const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),privacyNote:'Message bodies are omitted from export.',checks:data},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='offersignal-checks.json';a.click();URL.revokeObjectURL(a.href);};
$('#share-check').onclick=shareCheck;$('#clear-checks').onclick=()=>{if(confirm('Delete all locally saved OfferSignal checks?')){localStorage.removeItem(KEY);renderSaved();}};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});renderSaved();
