const RULES=[
  {id:'pay',weight:30,title:'Paying to get paid',why:'Legitimate employers do not require deposits, fees, or account “recharges” to release earnings.',patterns:[/pay (?:a |the )?(?:fee|deposit)/i,/recharge (?:your )?account/i,/unlock (?:your )?(?:earnings|commission)/i,/negative balance/i,/send (?:us |me )?money/i]},
  {id:'crypto',weight:22,title:'Cryptocurrency request',why:'FTC and FBI guidance identify cryptocurrency as a frequent payment rail in employment and task scams.',patterns:[/cryptocurrency|\bcrypto\b|\bbitcoin\b|\bethereum\b|\busdt\b|wallet address/i]},
  {id:'tasks',weight:20,title:'Game-like task work',why:'“Product boosting,” optimization, ratings, and repetitive task sets are documented task-scam patterns.',patterns:[/product boost/i,/app optimization/i,/complete (?:a |the )?set of tasks/i,/rate (?:products|images|apps)/i,/like (?:videos|posts)/i,/commission per task/i]},
  {id:'sensitive',weight:20,title:'Sensitive information too early',why:'Bank, tax, identity, and login details should not be the focus before a verified interview and hire.',patterns:[/social security|\bssn\b|bank account|routing number|driver'?s license|passport (?:copy|photo)|login credentials|password/i]},
  {id:'check',weight:24,title:'Check or equipment purchase',why:'A check followed by instructions to buy equipment or send money is a classic fake-check job pattern.',patterns:[/deposit (?:the |a )?check/i,/check (?:for|to buy) equipment/i,/purchase (?:your |the )?equipment/i,/preferred vendor/i,/refund (?:the |us )?difference/i]},
  {id:'urgency',weight:10,title:'Pressure to act immediately',why:'Artificial urgency reduces the time available for independent verification.',patterns:[/act (?:now|immediately)/i,/urgent(?:ly)?/i,/within (?:the next )?\d+ (?:minutes?|hours?)/i,/offer expires/i,/do not delay/i]},
  {id:'guaranteed',weight:12,title:'Unusually easy or guaranteed income',why:'Guaranteed returns or high pay for minimal, unspecified work deserve scrutiny.',patterns:[/guaranteed (?:income|earnings|profit)/i,/earn \$?\d+[\d,]* (?:daily|per day)/i,/no experience (?:needed|required).{0,40}(?:high pay|earn)/i,/easy money/i]}
];
const PERSONAL_DOMAINS=new Set(['gmail.com','yahoo.com','outlook.com','hotmail.com','icloud.com','proton.me','aol.com']);
export function analyzeOffer(input){
  const message=(input.message||'').trim(),label=(input.label||'').trim();if(!label)throw new Error('Add a role or company label.');if(message.length<20)throw new Error('Paste at least 20 characters from the message.');
  const matches=[];let score=0;for(const rule of RULES){const pattern=rule.patterns.find(p=>p.test(message));if(pattern){matches.push({id:rule.id,title:rule.title,why:rule.why});score+=rule.weight;}}
  const channel=input.channel;if(!input.applied&&['text','whatsapp','social'].includes(channel)){matches.push({id:'unsolicited',title:'Unexpected outreach',why:'Unexpected job messages through text, social media, WhatsApp, or Telegram are a documented warning pattern.'});score+=12;}
  const email=(input.senderEmail||'').trim().toLowerCase();const domain=email.includes('@')?email.split('@').pop():'';if(domain&&PERSONAL_DOMAINS.has(domain)){matches.push({id:'email',title:'Personal email address',why:'Recruiters for established companies generally use a verifiable corporate email domain.'});score+=12;}
  if(!input.interviewed){matches.push({id:'interview',title:'No real-time interview yet',why:'An offer or sensitive paperwork before a real interview deserves independent confirmation.'});score+=8;}
  if(input.verified)score-=12;score=Math.max(0,Math.min(100,score));const level=score>=50?'high':score>=20?'verify':'low';
  const config={low:{title:'Fewer common signals matched',summary:'The message matched few rules in this checklist, but that does not establish who sent it.'},verify:{title:'Verify carefully before proceeding',summary:'Several process or message patterns deserve independent confirmation.'},high:{title:'High concern — pause contact',summary:'Multiple documented scam patterns matched. Do not send money or sensitive information while you verify.'}}[level];
  const actions=['Find the employer’s website independently—do not use links or phone numbers from the message.','Confirm the role on the official careers page and contact the company through a number you found yourself.','Search the recruiter name, company, and a distinctive sentence from the message with “scam” or “complaint.”'];
  if(matches.some(x=>x.id==='pay'||x.id==='crypto'||x.id==='check'))actions.unshift('Do not pay, transfer cryptocurrency, deposit a check, or buy equipment on the sender’s instructions.');
  if(matches.some(x=>x.id==='sensitive'))actions.unshift('Stop sharing personal or financial information. If already shared, use IdentityTheft.gov or your country’s official identity-theft service.');
  return {label,message,senderEmail:email,channel,applied:!!input.applied,interviewed:!!input.interviewed,verified:!!input.verified,score,level,...config,matches,actions,createdAt:new Date().toISOString()};
}
export function safeParse(raw){try{const data=JSON.parse(raw);return Array.isArray(data)?data:[];}catch{return [];}}
